In [1]:
import numpy as np

In [ ]:
a.shape
(3, 5)
a.ndim
2
a.dtype.name
'int64'
a.itemsize
8
a.size
15
type(a)
<class 'numpy.ndarray'>
b = np.array([6, 7, 8])
b

In [ ]:
a = np.arange(15).reshape(3,5)# arange(15)# .reshape(3, 5)
a.size
type(a)

numpy.ndarray

In [ ]:
b =np.array([1,6,4])
b
type(b)


numpy.ndarray

## parte 2

In [ ]:
import numpy as np
a = np.array([2, 3, 4])
a
array([2, 3, 4])
a.dtype
dtype('int64')
b = np.array([1.2, 3.5, 5.1])
b.dtype
dtype('float64')

b = np.array([(1.5, 2, 3), (4, 5, 6)])
b
array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

np.zeros((3, 4))
np.ones((2, 3, 4), dtype=np.int16)

np.empty((2, 3)) 

In [ ]:
o = np.array([2,4,7,4,6])
o
type(o)

h = np.array([(2,3,4,5,65,97,54), (2,3,4,5,65,97,54)])
h.shape
h

me = np.array([[2,3], [2,4]], dtype=int)
me.shape

from numpy import pi
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)



(2, 2)

## Operacciones básicas

In [ ]:
a = np.arange(6)                    # 1d array
print(a)
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

a = np.array([20, 30, 40, 50])
b = np.arange(4)
b
c = a - b
c
b**2
10 * np.sin(a)
a < 35


In [ ]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B     # elementwise product
A @ B     # matrix product
A.dot(B)  # another matrix product

In [ ]:
P = np.array([[1,2],
              [3,4]])
B = np.array([[2, 0],
              [3, 4]])

print(P * B)
print( P @ B)
print(P.dot(B))

P.sum()
P.min()
# P.max()

[[ 2  0]
 [ 9 16]]
[[ 8  8]
 [18 16]]
[[ 8  8]
 [18 16]]


np.int64(1)

In [ ]:
n = np.array([2,3,4,5,4])
i = np.arange(5)
print(n)
print(i)

p= n-i
print('...............................')

print(p)

print(n**2)

l = n+i
l

[2 3 4 5 4]
[0 1 2 3 4]
...............................
[2 2 2 2 0]
[ 4  9 16 25 16]


array([2, 4, 6, 8, 8])

In [ ]:
t =np.arange(3)
t
l = np.arange(9).reshape(3,3)
l

k= np.arange(21).reshape(3,7)
k.shape

(3, 7)

In [ ]:
np.zeros([3,4])
np.arange(10,90,15)

f = np.linspace(0,9,11)
f.shape

(11,)

## Funciones universales

In [3]:
k = np.array([[24,42,8],[4,8,16],[2,3,1]])
y= (np.sqrt(k))
y

k[-1]

for v in k.flat:
    print(v)

print(k)
print(k.T)
print(k.T.shape)
print(k.shape)

print('sssssssssssssssssssssssssssss')
print(np.sqrt(k))



24
42
8
4
8
16
2
3
1
[[24 42  8]
 [ 4  8 16]
 [ 2  3  1]]
[[24  4  2]
 [42  8  3]
 [ 8 16  1]]
(3, 3)
(3, 3)
sssssssssssssssssssssssssssss
[[4.89897949 6.4807407  2.82842712]
 [2.         2.82842712 4.        ]
 [1.41421356 1.73205081 1.        ]]


In [ ]:
a = np.arange(12).reshape(3, 4)
b = a > 4
b  # `b` is a boolean with `a`'s shape
a[b]  # 1d array with the selected elements

In [7]:
m= np.arange(12).reshape(4,3)
b= m<6
b

m[b]=0
m

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 6,  7,  8],
       [ 9, 10, 11]])